INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Rondônia','RO','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Acre','AC','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Amazonas','AM','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Roraima','RR','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Pará','PA','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Amapá','AP','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Tocantins','TO','N');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Maranhão','MA','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Piauí','PI','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Ceará','CE','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Rio Grande do Norte','RN','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Paraíba','PB','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Pernambuco','PE','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Alagoas','AL','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Sergipe','SE','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Bahia','BA','W');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Minas Gerais','MG','E');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Espírito Santo','ES','E');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Rio de Janeiro','RJ','E');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('São Paulo','SP','E');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Paraná','PR','S');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Santa Catarina','SC','S');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Rio Grande do Sul','RS','S');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Mato Grosso do Sul','MS','C');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Mato Grosso','MT','C');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Goiás','GO','C');
INSERT INTO v0.estados (nome, id_estado, regiao ) VALUES ('Distrito Federal','DF','C');
