package com.univesp.pji310.euindico.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF545F73)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD8E3FB)
val md_theme_light_onPrimaryContainer = Color(0xFF111C2E)
val md_theme_light_secondary = Color(0xFF005BC4)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD8E2FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001A41)
val md_theme_light_tertiary = Color(0xFF625B77)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDFD5F7)
val md_theme_light_onTertiaryContainer = Color(0xFF1E1830)
val md_theme_light_error = Color(0xFF9F403D)
val md_theme_light_errorContainer = Color(0xFFFFDAD7)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410006)
val md_theme_light_background = Color(0xFFF8F9FF)
val md_theme_light_onBackground = Color(0xFF00345E)
val md_theme_light_surface = Color(0xFFF8F9FF)
val md_theme_light_onSurface = Color(0xFF00345E)
val md_theme_light_surfaceVariant = Color(0xFFE5EEFF)
val md_theme_light_onSurfaceVariant = Color(0xFF475266)
val md_theme_light_outline = Color(0xFF81B5F6)
val md_theme_light_inverseOnSurface = Color(0xFFEDF0F7)
val md_theme_light_inverseSurface = Color(0xFF000F21)
val md_theme_light_inversePrimary = Color(0xFFDAE6FE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF545F73)